sparcs-kaist/new-ara-api

ara/apps/session/urls.py
ara/apps/session/views.py

- And delete home(..) in session

Handling jwt w/ GET paramter

---

ara/apps/core/models/article_log.py
ara/apps/core/models/block.py
ara/apps/core/models/notification_log.py
ara/apps/core/models/report.py
ara/apps/core/models/scrap.py
ara/apps/core/models/vote.py
ara/apps/core/views/home.py
ara/apps/user/models/user/legacy.py

현재 formatting만 수정했는데도 서버가 정상작동하여 파이썬 버전을 올리려고 합니다.

upgrade python2 string formatting to python3

---

requirements.txt

Upgrade packages and write requirements.txt

---

.pylintrc
ara/apps/core/serializers/article.py
ara/apps/core/serializers/topic.py
ara/apps/core/urls.py
ara/apps/core/views/__init__.py
ara/apps/core/views/home.py
ara/apps/user/permissions/user.py
ara/ara/classes/sparcssso.py
requirements.txt

반대파가 많으면 철회하겠습니다. linter가 잡아준 쓰레기들만 커밋할게여...

Add Pylint

---

ara/apps/core/models/article.py

임시로 sanitize 함수를 비활성화 하고 json의 모든 텍스트 필드들을 순회하며 sanitize하는 식으로 바꿀 예정

Better XSS Sanitizing

---

tests/test_board.py

board에 대한 test code 작성
테스트 내용
1. board 생성 테스트

Add test_board

---

tests/test_articles.py

테스트 하는 것: 게시판 글에 대한 create, get 및 metadata 확인
테스트 상세 내용
1. Test number of articles in list
2. Test if anonymous writer's article is anonymous
3. Test if article's viewcount, pos/neg votes, and number of comments are properly updated
4. Test if article's contents (title, text, board etc.) are properly updated
5. Test: user other than writer tries to delete article
6. Test: writer tries to delete article
현재 6번 (글쓴이가 글을 지울 때) 통과 못함. 글쓴이가 delete할때, ArticleDeleteLog.objects.create를 사용하려고 시도 했으나, 이 후에도 article의 수가 줄지 않고 그대로임. 그래서 글을 delete하는 함수가 이게 아닌 것 같은데, 어떻게 delete 해야되는지 잘 모르겠음.

[WIP] Add test_articles

---

apps/core/urls.py
apps/core/views/__init__.py
apps/core/views/recent.py
tests/test_recent.py

Recently read articles 5개를 리턴하는 view를 만들었습니다.

Add view for recently read articles

---

apps/core/serializers/article.py
apps/core/serializers/block.py
tests/conftest.py
tests/test_block.py

다음과 같이 block test를 추가하였습니다.
1. block 개수 확인
2. block에 대해서 POST, GET, DELETE 메소드를 통한 생성, 보기, 삭제 확인 
3. 한 유저에 대한 중복 차단의 경우 확인
4. 쌍방향 차단이 가능한지 확인
5. 차단된 유저의 글과 댓글이 보이지 않는 것 확인
6. 차단된 유저의 익명글도 보이지 않는 것 확인
7. 차단 취소된 유저의 글은 보이는 것 확인
8. 자기 자신을 차단할 수 없는 것 확인
눈에 띄인 부분이 하나 있었습니다.
한 유저를 중복 차단할 경우, Block object가 여러개 생깁니다. 
급한 사항은 전혀 아니지만, 중복 차단을 방지하는 로직을 넣으면 좋을 것 같습니다.

Add block tests

---

apps/core/views/recent.py

- 기존 쿼리의 경우 `@property`를 써서 서버에서 정렬을 했는데, `Case()` 문을 써서 DB에서 정렬을 하도록 변경했습니다.
- Pagination 추가
- 쿼리를 더 최적화? (테스트가 좀 느림)

Optimize queries, add pagination for recently_read_articles

---

apps/core/urls.py
apps/core/views/recent.py
tests/test_recent.py

Fix recent article pagination

---

apps/core/permissions/block.py
apps/core/views/viewsets/block.py

로그인한 사용자만 Block endpoint들에 접근할 수 있게 합니다.
이게 왜 문제였냐면...
- POST 요청 시 request.user가 AnonymousUser여서 500 발생
- 차단 목록 가져오기가 됨 (403이 뜨는 것이 직관적)

Add IsAuthenticated permission to Block

---

ara/settings/djangorestframework.py
ara/settings/prod/__init__.py

production 환경에서는 BrowsableAPIRenderer 사용을 지양하는 것이 좋을 것 같습니다.

Disable BrowsableAPIRenderer in production envrionment

---

tests/conftest.py
tests/test_articles.py

테스트 코드 보다보니 관리자 fixture의 프로필 설정이 잘못되어 있어 수정했습니다.

Fix profile setup for admin test fixture

---

ara/log/log_object.py

LogObject들에 __repr__를 추가합니다.
이제 센트리에서 로그가 예쁘게 뜹니다.

Add __repr__ for LogObjects

---

.editorconfig
.pre-commit-config.yaml
poetry.lock
pyproject.toml

commit 시에 black(code formatter), pylint 을 실행하는 깃훅을 부착했습니다.
.editorconfig 도 붙였습니다.

Add black and pylint githooks

---

ara/settings/sentry.py
poetry.lock
pyproject.toml

sentry 에서 celery 실행 도중 발생한 에러를 제대로 볼 수 없는 문제가 있습니다.
해당 에러들을 좀 더 자세히 볼 수 있도록 Celery & Redis Integration 을 활성화합니다.

Enable sentry integrations

---

apps/user/views/viewsets/user.py
ara/classes/sparcssso.py

Sparcs SSO 에서 에러 발생하여 로그인 실패 시에 적절한 에러 메시지를 response 로 내려주도록 변경함

Add proper error message when fail to login

---

README.md
docker-compose.example.yml

- update README
- fix wrong comment in docker-compose.example.yml

update management info

---

buildspec.yml

https://github.com/sparcs-kaist/new-ara-api/pull/185 와 동일한 PR입니다. develop 에 머지를 했어야 하는데, master 에 머지를 해버렸습니다.
https://github.com/sparcs-kaist/new-ara-api/pull/185 를 victory 님이 이미 approve 해주셨기에 이 PR은 바로 merge합니다.

Replace deprecated command

---

poetry.lock
pyproject.toml

Add html5lib dependency explicitly

---

apps/core/management/scripts/portal_crawler.py

포탈 로그인 방식이 바뀌어서 크롤러가 터졌는데, 새로운 방식에 맞게 로그인 코드를 수정합니다.
여담으로 포탈이 IAM v2로 바뀌었으니 TLS 버전 문제로 인한 오류는 더 이상 발생하지 않을것 같습니다. (참고: https://www.ssllabs.com/ssltest/analyze.html?d=iam2.kaist.ac.kr&latest )

Fix KAIST portal login

---

.docker/supervisor-app.conf
Dockerfile
apps/user/serializers/user_profile.py
apps/user/views/me.py

리디자인된 마이페이지를 위해서 BaseUserProfileSerializer에 3개 필드를 추가하였습니다:
- 사용자가 작성한 글 수 (num_articles)
- 사용자가 작성한 댓글 수 (num_comments)
- 사용자가 받은 공감 수 (num_postive_votes)
이제 /api/me를 호출했을때 아래와 같이 이 3개필드가 추가되어 나타납니다.

BaseUserProfileSerializer에 마이페이지용 필드 추가

---

apps/core/serializers/article.py
tests/test_recent.py

- Fix #248
- Added test that reproduces #248 bug

Fix IndexError on not enough recents

---

apps/core/models/article.py
apps/core/models/comment.py
apps/core/models/signals/on_delete_cascade.py
apps/core/serializers/comment.py
ara/db/models.py
ara/locale/en/LC_MESSAGES/django.po
ara/locale/ko/LC_MESSAGES/django.po
tests/test_comments.py

Handle #239 
Add new model class 'AllQueryMetaDataModel' for Comment table.

Preserve sub_comment when parent_comment deleted

---

apps/core/views/viewsets/article.py
apps/core/views/viewsets/comment.py
ara/settings/api.py
tests/test_articles.py
tests/test_comments.py

Hotfix for #275 
Production에서도 익명게시판의 id가 9가 맞나요?

Prevent anonymity breakout

---

apps/core/views/viewsets/comment.py

Ctrl CV 이후 수정하지 않은 부분이 있었습니다. 어떻게 이걸 그냥 넘어갔지...?

Fix wrong model name in checking code

---

apps/core/serializers/article.py

ArticleSerializer#get_side_articles_of_recent_article의 쿼리가 느린 것을 해결합니다. #199 에서 썼던 방식 그대로입니다.
왠만하면 그냥 두려고 했는데 게시물 띄우는게 6초 걸리고 이래서 작업했습니다.
#245 에서 만든 테스트 통과하기는 하는데, 이게 이렇게 쉽게 패치될 리가 없을것 같아서 확인 좀 부탁드립니다.

Use aggregated query for from_view=recent side articles

---

ara/settings/dev/__init__.py
ara/settings/prod/__init__.py
tests/conftest.py
tests/test_report.py

https://www.notion.so/sparcs/4-4d0e50afe6c846cc96a43c4b6780a98a
dev와 Prod 모두 신고 수에 의한 자동 숨김처리 기준을 4로 하향했습니다.
테스트케이스도 맞게 수정하였습니다.

Change report threshold to 4

---

apps/core/views/viewsets/article.py
ara/settings/api.py
tests/test_articles.py
tests/test_block.py

Exclude blocked user articles in anonymous board

---

apps/core/serializers/article.py

신고로 숨겨진 글의 첨부파일을 보내지 않도록 수정하였습니다.

Hide attachments in report-hidden articles

---

apps/core/views/viewsets/article.py

communication article이 생성될 때 save()가 호출되지 않는 버그가 있어서, 추가하였습니다.

Save communication article after creation

---

apps/core/management/scripts/reminder_email_for_reply.py

new-ara@sparcs.org도 리마인더 메일 수신자로 추가했습니다

Add newara email as reminder email receiver

---

.github/workflows/generate-docker-tag.sh

dev에 머지시 github action이 실패하는 오류를 고쳤습니다.

Fix env passing in github action

---

.pre-commit-config.yaml
ara/locale/en/LC_MESSAGES/django.po
ara/locale/ko/LC_MESSAGES/django.po
manage.py
poetry.lock
pyproject.toml

1. Add pre-commit hooks for [poetry](https://python-poetry.org/docs/pre-commit-hooks/).
2. Update [`.po` files](https://docs.djangoproject.com/en/3.2/topics/i18n/translation/).
3. Upgrade packages.
4. Add missing packages.
5. Refactor `manage.py` file.

Upgrade packages and manage files

---

apps/core/views/viewsets/article.py

[참고 카드](https://www.notion.so/sparcs/N-1-Query-Sentry-4fb18c281e804ed08aa9a25fb3d32737)

Add prefetch attachment to resolve nplus1

---

apps/core/filters/article.py

- Add URL parameter for articles: `/articles/?board={parent_board__slug}` (e.g., `/articles/?board=talk`)

Add board slug to article filter parameter

---

apps/core/views/viewsets/board.py

- Use `BoardDetailActionSerializer` for GET `/boards/{board__slug}`.

Use detail serializer for GET method

---

Pipfile
Pipfile.lock

feat(mypy): Add typing-extensions

---

apps/core/views/home.py
apps/core/views/viewsets/board.py

- Fix `GET /home` N+1 Query problem
- Fix `GET /boards` N+1 Query problem

Fix home & board group N+1 Query problem

---

apps/core/serializers/article.py

* fix: bugfix for top query
* fix: typo error

Deploy v3.4.5

---

apps/core/management/scripts/portal_crawler.py

포탈 크롤러 업데이트 이후 발생하는 동명이인 버그 (Integrity error)를 fix하였다.

fix_portal_crawler integrity error

---

Pipfile
Pipfile.lock
apps/user/views/viewsets/user.py
ara/authentication.py
ara/settings/dev/__init__.py
ara/settings/django.py

Reverts sparcs-kaist/new-ara-api#492

Revert "Revert "add jwt authentication" for realeased"

---

Pipfile
Pipfile.lock
apps/user/views/viewsets/user.py
ara/authentication.py
ara/settings/dev/__init__.py
ara/settings/django.py

Reverts sparcs-kaist/new-ara-api#493
v3.6.1을 위해서 다시 revert 합니다. (보안 이슈)

Revert add jwt authentication" for realeased""

---

Pipfile
Pipfile.lock
apps/user/views/viewsets/user.py
ara/authentication.py
ara/settings/dev/__init__.py
ara/settings/django.py

add jwt authentication 복구

---

apps/kaist/portal/worker.py

포탈 크롤러에서 slack 알림 전송과 관련된 부분에 try-except를 처리하였습니다.

add try-except to slack alert

---

Pipfile
Pipfile.lock
apps/user/views/viewsets/user.py
ara/authentication.py
ara/settings/dev/__init__.py
ara/settings/django.py

Reverts sparcs-kaist/new-ara-api#495

Revert Jwt for v3.6.2 realease

---

Pipfile
Pipfile.lock
apps/user/views/viewsets/user.py
ara/authentication.py
ara/settings/dev/__init__.py
ara/settings/django.py

Reverts sparcs-kaist/new-ara-api#498
v3.6.2 배포 이후 jwt를 원상복구 하였습니다.

jwt after 3.6.2 release

---

ara/settings/dev/__init__.py

프론트엔드 마이그레이션을 위해 http를 사용하여 쿠키 전달이 가능하도록 수정합니다.

modify dev setting for front-end migration

---

ara/settings/dev/__init__.py

Reverts sparcs-kaist/new-ara-api#507

Revert "modify cookie secure setting"

---

ara/settings/dev/__init__.py

Reverts sparcs-kaist/new-ara-api#505

Revert "add allowed host option"

---

apps/chatting/models/expired_message.py
apps/chatting/models/mebership_room.py
apps/chatting/models/message.py
apps/chatting/models/room.py
apps/chatting/models/room_invitation.py
apps/chatting/models/room_permission.py

Basic DB field for chatting tf

---

apps/chatting/permissions/dm.py
apps/chatting/permissions/invitation.py
apps/chatting/permissions/message.py
apps/chatting/permissions/room.py
apps/chatting/views/viewsets/room.py

API 별 ViewSet에 접근 가능한 permission 관련 class 들을 정의합니다.

[Chat TF] Permission Classes

---

apps/chatting/models/room_invitation.py
apps/chatting/permissions/invitation.py
apps/chatting/serializers/invitation.py
apps/chatting/serializers/room.py
apps/chatting/views/router.py
apps/chatting/views/viewsets/__init__.py
apps/chatting/views/viewsets/invitation.py
apps/chatting/views/viewsets/room.py

[Chat TF] API : invitation

---

apps/chatting/views/viewsets/room.py
apps/user/serializers/user_profile.py
apps/user/views/viewsets/user_profile.py

채팅 기능과 관련된 기본적인 API들을 모아 version1을 완성합니다.

[Chat TF] API (HTTP) V1 : basic apis for messaging.

---

apps/user/views/viewsets/user.py
ara/authentication.py
ara/settings/dev/__init__.py
ara/settings/django.py
ara/settings/env.py

One App 팀의 요청으로, jwt secret와 uid를 기반으로 한 인증 로직을 추가합니다.

[One App] : 원앱 JWT Secret & Uid 기반 인증 관리 로직 추가

---

apps/chatting/views/viewsets/room.py

room / {id} 엔드포인트에서 특정 room 의 세부 정보를 보다 더 자세히 return 하도록 하였습니다. (채팅방에 참여한 User 정보와, 참여한 유저 정보 추가)

[Chat TF] Chat Room API Retrieve

---

apps/chatting/views/viewsets/room.py

chat room을 가져오는 get api에서 기본적으로 ordering이 들어오지 않았을 때,
recent_message_at 혹은 created_at을 기준으로 가장 최근 것 부터 위로 오도록 정렬 속성을 추가하였습니다.

[Chat TF] Add Order to chat room get api

---

apps/chatting/views/viewsets/room.py

[fix] Fix import path of greatest module

---

apps/chatting/models/room.py
ara/db/models.py

포스터, 등의 만료 기한이 있는 게시판을 처리하기 위해서 Meta Data model 에서 삭제 시점이 미래로 되어 있는 경우도 존재하는 DB에 포함되는 것으로 처리하였습니다. (기타 예약삭제 기능 구현)

Modify Meta Data Model's Query Set Logic

---

apps/core/serializers/article.py
apps/core/views/viewsets/article.py

api 응답에서 article metadata를 사용할 수 있도록 합니다.

fix aritcle metadata

---

apps/chatting/views/viewsets/dm.py
apps/chatting/views/viewsets/room.py

add leaved room filtering logic
