sparcs-kaist/new-ara-api

- apps/core/views/viewsets/notification.py
- tests/conftest.py
- tests/test_notification.py
notification에 대한 test code 작성
테스트 내용
1. 게시글에 댓글이 달렸을 때, 댓글에 대댓글이 달렸을 때 notification이 잘 생성 되었는지 테스트
2. notification를 성공적으로 읽을 수 있는지 테스트 (notification들 중 하나만 읽을 때). read 함수 테스트
3. notification를 성공적으로 읽을 수 있는지 테스트 (notification 모두 읽을 때). read_all 함수 테스트
4. (미완) notify_commented 함수 테스트
안 되는 것
1. request status는 200 반환되나 num_item가 0이 나와 맞지 않는 상태 (object 생성은 잘 되지만 queryset에 추가가 안 되는 것 같음)
2. post로 http request 보내면 404가 뜸. viewset에서 queryset 구성이 잘 안 되는 것을 확인함.
3. 2번과 마찬가지
> Add test_notification

- apps/core/serializers/article.py
- apps/core/serializers/comment.py
- tests/test_comments.py
댓글에 대하여 다음과 같은 테스트를 추가하였습니다.
1. get으로 댓글 리스트 가져오기
2. post로 댓글/대댓글 생성하기
3. 댓글/대댓글의 생성/삭제에 따른 게시글의 댓글 수 확인 (comments_count, nested_comments_count)
4. delete로 댓글/대댓글 삭제 (작성자/비작성자일 경우)
5. 익명 댓글의 익명성 확인 
6. 투표 기능 확인 (투표 수, 중복 투표 불가능, 취소, 재투표)
너무 기본적인 기능들만 테스트하는 것 같은데, 혹시 필요없어 보이는 테스트는 말씀해주시면 감사하겠습니다.
앞으로 comment_log와 best_comment에 대한 테스트를 추가할 계획입니다.
> Add tests for comments

- apps/core/views/viewsets/article.py
- tests/conftest.py
- tests/test_user.py
다음과 같이 User 모델에 대한 테스트를 추가하였습니다.
- API를 통해 사용자 프로필의 조회 및 변경이 잘 이루어지는지 테스트합니다.
- 사용자의 게시물 필터에 따라 게시물 목록에서 필터링이 잘 되는지 테스트합니다.
- 사용자 필터에서 가능한 4가지 경우와, 게시물의 정치글/성인글 여부에 대해 총 16가지 경우를 테스트합니다.
이외 `test_filter_articles_read`, `test_filter_articles_best`는 각각 게시물 읽기, 베스트 게시물 목록에 대해 동일한 경우를 테스트합니다.
> Add User tests

- apps/core/views/viewsets/article.py
- tests/test_articles.py
자신이 작성한 게시물에는 좋아요, 싫어요를 할 수 없게 합니다. 요청을 보낼 경우 403을 반환합니다.
- 관련 테스트 추가 (`test_self_vote`)
- 투표 view에 게시물 작성자, 사용자 pk 비교 추가
> Add checks to block self-voting

- apps/core/filters/article.py
- tests/test_article_search.py
- 제목 포함 or 본문 포함 or 닉네임 일치로 Article 검색 필터 추가
- 기존 `get_title_or_content__contains` 포함해 검색 필터에 대한 테스트 추가
- 쿼리 최적화는 아직 필요
> Add search filter for articles

- tests/test_recent.py
Recent url이 c905c4c 에서 바뀌었는데, 그래서 404가 뜨던 테스트들의 url을 고쳐주었습니다.
> Fix failing recent tests

- apps/core/models/article.py
- apps/core/views/viewsets/article.py
- apps/core/views/viewsets/comment.py
ArticleViewSet list action 에서 nested_comments_count 계산하는 부분의 쿼리를 최적화했습니다.
before:
after:
> optimize query of ArticleViewSet list action

- apps/core/serializers/article.py
- apps/core/views/home.py
[SmallBoard component](https://github.com/sparcs-kaist/new-ara-web/blob/dev/src/components/SmallBoard.vue) 에서 사용하는 field는 id, title, created_by 밖에 없습니다.
하지만, ArticleListActionSerializer 에서 요구하고 쿼리하는 필드가 너무 많아서 HomeView가 느려지는 감이 있어 PR을 작성했습니다.
before:
after:
> Use BestArticleListActionSerializer for optimizing queryset of HomeView

- apps/core/models/article.py
- apps/core/views/viewsets/article.py
- apps/core/views/viewsets/comment.py
https://github.com/sparcs-kaist/new-ara-api/pull/122 머지 후에 order_by('-created_at')이 적용되지 않는 것을 해결하기 위한 롤백 PR입니다.
django.db.models.Subquery, django.db.models.Count, django.db.models.OutRef 등등 다양하게 시도해보았지만 적당한 해결책이 없어서 
https://github.com/sparcs-kaist/new-ara-api/tree/feature/save-comment-count 와 같은 방식으로 해결하려 합니다.
> Rollback optimize article list

- apps/user/serializers/user.py
현재 뉴아라에서는 다른사람의 이메일을 사용하는 일이 없어 public user serializer 에서 제외합니다.
> Delete email field in public user serializer

- apps/user/serializers/user_profile.py
profile.user_id = profile.id 라서 필요없는 중복을 없앴습니다.
> Delete using profile.user_id

- apps/user/views/viewsets/user.py
로그아웃된 상태에서 한 번 더 로그아웃을 시도할 때 500 Internal Server Error가 나는 것을 방지하는 코드입니다.
일반적인 상황에서는 발생하지 않지만, 방어적인 프로그래밍 차원에서 넣었습니다.
> Add defensive code for avoiding try to logout with anonymous user

- apps/core/management/scripts/portal_crawler.py
- apps/user/views/viewsets/user.py
@HelloWorld017 가 포탈에서 크롤링해온 글들의 링크가 plain text로 나오는게 있어 하이퍼링크화 작업을 예정하고 있었는데, 프론트에서 처리하기보단 처음 긁어올때부터 백엔드에서 처리해주는게 부하가 적을 것 같아 작업했습니다.
이미 링크화가 되어있는건 태깅을 건너뛰어줘야하는데, 포탈 공지에서 그런 경우는 a 태그의 href attribute이거나 img 태그의 src attribute 두가지만 있을거라고 일단 예상하고 작업했습니다.
Help-needed:
- 혹시 링크가 이미 태그 안에 있는지 확인하는 작업을 일반화할 수 있거나,
- ~위 두가지 (a-href, img-src) 외 또 생각나는 경우가 있으시면 알려주시면 좋을 것 같습니다.~
-> recursive하게 child다 불러와서 traverse하는걸로 수정했어요.
고치고 싶었던 예시: https://ara-beta-dev.netlify.app/post/440?from_view=all 의 수강취소쪽 링크 등이 plain text로 나옴
> If url, change to href

- apps/core/documents.py
- apps/core/filters/article.py
- apps/core/serializers/article.py
main_search에 붙어 있는 로직을 elasticsearch query로 처리하도록 수정했습니다. 
apps.core.documents의 ArticleDocument.get_main_search_id_set에서 반환되는 검색결과 개수를 최대 500개로 제한하여, 실행이 적절한 시간 안에 끝나도록 합니다.
> Limit result of main_search size to 500

- apps/user/views/viewsets/user.py
1. 카이포탈 인증 이전, 회원가입을 시도했던 회원 (나중에 카이포탈 인증 후 다시 로그인 시도)
2. 아직 승인 이전, 회원가입을 시도했던 공용 계정 회원
> Allow later authenticated user login

- apps/user/views/me.py
CSRF 토큰이 셋팅되지 않은 상태에서 일부 요청이 보내져 오류가 나는 상황이 있습니다.
이를 해결하기 위해 클라이언트에서 한번쯤 보낼 요청 (`/api/me`)에서 csrf 토큰을 설정하도록 했습니다.
Permission을 쓰면 로그인 되지 않은 상태에서 토큰 설정이 되지 않아 뷰에서 직접 권한을 체크하도록 변경했습니다.
> Ensure CSRF token is set by /api/me

- apps/user/views/viewsets/user.py
중복 닉네임의 경우 `즐거운 펭귄` -> `즐거운 펭귄_0a7b` 와 같이 해쉬를 붙여주도록 변경했습니다.
보안이 필요한 해쉬는 아니니 타임스탬프와 기존 닉네임만 이용해서 sha-256 해쉬를 만들고, 맨 앞 4자리만 붙여줬습니다.
테스트 케이스를 추가해줘야 하는데, `_make_random_name` 자체가 랜덤이다 보니 붙이기가 굉장히 애매하네요. 의견 부탁드립니다 🙏
> 중복 닉네임에 번호 대신 해쉬를 부여

- apps/core/views/home.py
- tests/test_home.py
로그인되어 있지 않은 상태에서 `/api/home` 요청을 보냈을 때
```
'AnonymousUser' object has no attribute 'profile'
```
오류가 발생하는 것을 수정하였습니다.
참고로 해당 이슈의 직접적인 원인은 `BaseArticleSerializer`의 `validate_hidden`에서 비로그인 상태에 대한 고려가 없어 발생하는 문제입니다. 향후 비로그인 상태에서 해당 serializer를 사용해야 한다면 수정이 필요합니다.
> HomeView 퍼미션 추가

- apps/core/views/viewsets/notification.py
로그인 하지 않은 사용자가 NotificationViewSet의 List나 Detail api 호출 시에 발생하는 에러 해결.
어떤 과정으로 해당 API를 호출하는지는 잘 모르겠음
> Handle not logged in user

- apps/core/admin.py
ko_description과 en_description은 Article에 존재하지 않는 필드이나, 복붙하면서 실수로 들어간 듯 함.
> Remove not exists fields

- apps/user/views/viewsets/user.py
SSO 쪽에서 SNS로 우선 회원가입을 진행하고, 그 이후에 카이스트 인증을 한 경우,
이메일은 @sso.sparcs.org 로 끝나는 랜덤 이메일이 박히고, 나중에 kaist_info 만 채워지는 듯 합니다.
카이스트 구성원임이 인증된 경우, 유저 이메일에는 웬만하면 카이스트 메일이 박히는 것이 좋은 것 같아 (마이페이지에서 볼때에도) 다음을 추가합니다.
> 유저 이메일 필드는 웬만하면 카이스트 메일로 박기

- apps/core/views/viewsets/article.py
좋아요 취소 버튼이나 싫어요 취소 버튼을 빠른 시간 내에 여러번 클릭해 vote_cancel action이 여러 번 발생했을 때 Vote.DoesNotExist exception이 발생하지 않도록 변경하였습니다.
> Handle case of Vote already deleted by other previous vote_cancel action

- apps/user/views/viewsets/user.py
https://github.com/sparcs-kaist/new-ara-api/pull/182 의 버그를 수정한 PR입니다.
InvalidSsoLoginView로 redirection 시켜줘야 하는 경우 중 한 가지가 누락돼 수정하였습니다.
좀 더 자세히는 아래와 같습니다.
- is_kaist or is_manual 에 해당하지 않는 사용자
즉, kaist 구성원도 아니고, manual 하게 생성한 사용자도 아닌 사용자(not is_kaist and not is_manual)
> Fix bug related to redirect InvalidSsoLoginView

- apps/core/views/viewsets/article.py
ArticleViewSet의 recent action의 쿼리를 최적화 했습니다.
- ArticleSerializer 대신 ArticleListActionSerializer 를 사용해 사용하는 필드만을 serialize 함.
- UserProfile을 select related로 join 해서 긁어옴.
frontend develop 브랜치에서 실행 결과 문제 없었습니다.
테스트를 위해서 CI가 작동 안하는 문제를 해결한 https://github.com/sparcs-kaist/new-ara-api/pull/185 위에 올렸습니다. 머지할 때는 분리해서 머지하겠습니다.
> Optimize queryset of ArticleViewSet's recent action

- apps/core/admin.py
- apps/core/views/viewsets/report.py
1. 댓글 신고할때도 이메일에 사유 들어가도록 수정
2. 신고 이메일에 html말고 내용만 오도록 
3. admin 페이지에 댓글 페이지 넣음 (신고된 댓글을 삭제해야할 경우 대비)
> [#191] 신고 이메일 포맷 수정 및 어드민 페이지에 댓글 추가

- apps/core/serializers/article.py
- apps/core/views/viewsets/article.py
Recent view에서 최근 조회 일시를 가져오기 위해 서브쿼리를 사용하고 있었는데, 대신 aggregation을 사용합니다.
Django ORM으로는 temp table에 join하는 것이 어려워 raw query를 써서 아래와 같은 복잡한 점이 몇가지 생깁니다:
- `filter_queryset`에서 쿼리셋을 만들지 않고 action 함수에서 직접 만듭니다.
- 날쿼리는 paginator에서 처리할 수가 없어서 paginator를 따로 가져오고, 날쿼리에서 나온 데이터를 꽃아주는 방식으로 pagination을 구현했습니다.
- join 안하고 aggregate된 값을 바로 사용하도록 serializer를 변경했습니다.
Explain plan상으로는 확실히 빨라지는데요 (total cost 22.61 → 5.88), 아무래도 날쿼리로 인한 코드 퀄리티 저하가 좀 있는 것 같아 고민이 됩니다. 또 제 로컬에 있는 recent 테이블이 그렇게 크지 않아서 실제 성능 향상이 어느정도인지도 가늠하기 힘들고요. 프로덕션 디비를 가져와서 로드 테스팅을 해봐도 좋을 것 같습니다.
> Optimize recent query by using aggregation

- apps/core/serializers/article.py
- apps/core/serializers/comment.py
< 7/5 회의시간 논의 >
익명글/댓글의 경우 id를 해싱해서 내려주게 되면서 프론트에서 이 글/댓글이 본인글인지 확인이 불가능해짐.
그래서 is_mine 필드를 serializer에 넣어서 함께 내려줌.
이 필드를 통해 프론트는 유저가 이 글/댓글을 수정/삭제 할 수 있는지 판단할 수 있음.
is_mine은 boolean 으로 내려갑니다. (true/false)
> article, comment serializer에 is_mine 추가

- apps/core/views/viewsets/article.py
마이페이지에서 내가 쓴 글을 볼때, 그리고 게시글에서 작성자 이름을 클릭해서 그 작성자의 모든 글을 볼때 아래 api를 사용합니다:
api/articles/?created_by=1
다른 사용자의 글 목록을 조회할 때는 익명 게시글이 보이지 않고, 자신의 작성 글 목록에는 자신이 작성한 익명 게시글들이 보이도록 수정하였습니다.
> 다른 사용자의 게시글 목록을 조회할 때, 익명 게시글 제외

- apps/core/models/article.py
- tests/test_comments.py
기존엔 익명 게시글에 hashed user id를 넣지 않았으나, 필요하게 되어 hashed user id를 추가합니다.
> 익명 게시글에 hashed user id 추가 

- apps/core/views/viewsets/article.py
- apps/core/views/viewsets/scrap.py
- Fixed search on scraps
- 새로운 filterset을 만들기보다, 어차피 scrap의 경우 이미 scrapped_by로 queryset이 filter되고 있는 만큼 거기에 같이 얹어가도록 구현했습니다. 
- Fixed search on recents
- es에서 얻어온 id_set을 이용해 subquery 단에서부터 미리 글을 거를 수 있도록 구현했습니다. 
- `search_restriction_sql`을 str.join 등을 이용해 직접 만들고 있는데, 이렇게 하는 것이 최선일지 의견 남겨 주시면 감사하겠습니다.
> Fix search on recents and scraps

- apps/core/models/article.py
- apps/core/models/comment.py
- tests/test_user.py
익명 글/댓글에 대한 프로필 사진의 경우, PublicUserProfileSerializer를 거치지 않아 프로필 사진 링크가 미완성이었습니다.
따라서 익명 글/댓글의 프로필 사진 링크를 완성하였습니다.
> 익명 게시글 프사 링크 제대로 안들어가는 문제 해결

- apps/core/admin.py
특정 id로 작성된 모든 article/comment를 삭제해달라는 문의가 자주 들어옵니다.
지금은 각 article을 제목으로 찾아 일일히 삭제해야해서 번거롭습니다.
그래서 search field에 user id를 추가하고자 합니다.
> Admin page의 게시글, 댓글 페이지에서 username으로 search하는 기능 추가

- apps/core/serializers/article.py
- tests/test_scrap.py
issue #228
fromview=scrap 에서 보이는 side_article의 after,before를 결정짓는 순서가 article table의 created_at으로 되어있던 것을 scrap table의 created_at을 참조하도록 변경하였습니다.
테스트코드 작성하였습니다.
> scrap의 side_articles 문제 해결

- .coveragerc
- Makefile
- apps/core/models/article.py
- apps/core/permissions/article.py
- apps/core/serializers/article.py
- apps/core/views/viewsets/article.py
- tests/test_articles.py
- tests/test_report.py
게시물이 숨겨졌을 때에 대한 API를 보다 일관되게 정리합니다. ([Notion Ticket](https://www.notion.so/sparcs/2693dc9cd9fd48ffbcfb82e8523b3823))
모두 GET `/articles/:id`에 대한 수정사항입니다.
- `hidden_title`, `hidden_content` 필드 삭제 (참고: 숨겨진 상태일 경우 `title`, `content` 모두 null)
- `string[]` 타입의 `why_hidden` 필드를 추가하여 숨겨진 이유들에 대한 목록을 반환 (값은 하단 참고)
- 숨겨진 내용을 보고자 할 때에는 query에 `override_hidden` 키를 주면 됨
- 솜겨진 내용을 볼 수 있는지 (cf. 신고로 숨겨진 글은 숨기기를 풀 수 없음) 여부는 `can_override_hidden` 값을 반환
애초에 숨겨지지 않았던 게시물은 `can_override_hidden`이 null임.
참고) 숨겨진 글을 보더라도 why_hidden은 유지되기 때문에 원래부터 볼 수 있는 글인지, override한 글인지 응답 내용으로 구분이 가능
- `ADULT_CONTENT`
- `SOCIAL_CONTENT`
- `REPORETED_CONTENT`
- `BLOCKED_USER_CONTENT`
논의되었던 ACCESS_DENIED_CONTENT의 경우 Serializer에 도달하기 전 Permission에서 403 요청을 보내고 끝내버리기 때문에 굳이 추가될 필요가 없었습니다 (=프런트 팀에서 고려하지 않아도 됨)
미래에 추가로 권한 관리가 들어갈 수 …
> Unified hidden messages for articles

- apps/core/serializers/article.py
HomeView에서 오늘의 인기글 / 금주의 인기글에서 hidden 관련 필드가 없어서 추가합니다.
여기서 사용하는 BestArticleListActionSerializer에 필드 property가 없어서 문제였습니다.
HomeView 자체에 테스트가 없어서 (see #259) 한번에 짜려고 테스트는 안짰습니다.
Fixes #260
> Add hidden-related columns to BestArticleListActionSerializer

- apps/core/models/comment.py
- apps/core/serializers/comment.py
- apps/core/views/viewsets/article.py
- apps/core/views/viewsets/comment.py
- ara/locale/en/LC_MESSAGES/django.po
- ara/locale/ko/LC_MESSAGES/django.po
- tests/test_articles.py
- tests/test_comments.py
- tests/test_report.py
삭제되거나 신고에 의해 숨겨진 게시글/댓글에 대한 수정 요청을 거부합니다.
이슈 #253 에 설명된 작업을 구현하였습니다.
테스트 케이스 작성을 위해 water님께서 PR #254 에서 작업하신 내용이 필요하여, merge하였습니다.
게시글:
- 삭제된 게시글에 대한 POST 요청:
- 기존 로직으로도 update() 중 get_object()에서 404가 뜨며, 처리되지 않습니다. (로직 수정 필요없음)
- 신고로 숨겨진 게시글에 대한 POST 요청:
- viewsets/article.py에서 update()를 overriding 하여, `is_hidden_by_reported()`일 경우 HTTP 405를 리턴합니다.
댓글:
- 게시글과의 차이점:
- 사용자에게 `삭제된 게시글입니다`를 보여주기 위해 DB에서 댓글을 삭제하지 않도록 구현되어 있습니다. 따라서, 삭제된 게시글에 대해 404가 뜨지 않습니다.
- 삭제 / 신고 숨김된 게시글에 대한 POST 요청:
- viewsets/comment.py에서 update()를 overriding 하여, `is_deleted() or is_hidden_by_reported()`일 경우 HTTP 405를 리턴합니다.
> Prevent modification of hidden/deleted articles and comments

- apps/core/models/article.py
- apps/core/models/comment.py
- tests/test_articles.py
- tests/test_comments.py
프런트팀에서 요청한 것과 같이 `why_hidden` 항목을 업데이트합니다.
반영된 순서는 **DELETED_CONTENT (Comment만 해당)** > REPORTED_CONTENT > BLOCKED_USER_CONTENT > ADULT_CONTENT (Article만 해당) > SOCIAL_CONTENT (Article만 해당) 입니다.
> Update Article, Comment hidden reason ordering

- apps/core/admin.py
admin page에서 many to many field들이 dropdown으로 보여지기 때문에 timeout이 발생합니다.
기존에 dropdown으로 보여줬던 필드들을 `raw_id`만 보여주도록 수정합니다.
참고: 
Django docs: [ModelAdmin.raw_id_fields](https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#django.contrib.admin.ModelAdmin.raw_id_fields)
> Admin page 상세보기에서 timeout 문제 해결

- apps/core/views/viewsets/article.py
- apps/core/views/viewsets/comment.py
- apps/core/views/viewsets/report.py
- ara/locale/en/LC_MESSAGES/django.po
- ara/locale/ko/LC_MESSAGES/django.po
- tests/conftest.py
- tests/test_articles.py
- tests/test_comments.py
아래와 같이, O는 허용되고 X는 허용되지 않도록 구현합니다.
각 케이스를 확인하는 테스트코드도 작성합니다.
신고로 숨겨진 글:
- 신고 X
- 좋아요/싫어요 X
- 삭제 X
- 댓글/대댓글 O
삭제된 글:
- 신고 X
- 좋아요/싫어요 X
- 삭제 X
- 댓글/대댓글 X 
신고로 숨겨진 댓글:
- 신고 X
- 좋아요/싫어요 X
- 삭제 X
- 대댓글 O
삭제된 댓글:
- 신고 X
- 좋아요/싫어요 X
- 삭제 X
- 댓글/대댓글 O
> Prevent vote/report/comments on deleted/hidden articles/comments

- poetry.lock
- pyproject.toml
현재 버전인 3.2.4에 SQLi 이슈가 있습니다. https://docs.djangoproject.com/en/3.2/releases/3.2.5/
3.2.9까지 breaking change 없이 쭉 버그 픽스라 가장 최신으로 올렸습니다.
> Bump Django to 3.2.9

- apps/core/views/viewsets/comment.py
- tests/test_comments.py
백엔드에서 댓글의 익명 여부는 프론트에서 보내주는 is_anonymous 필드로 결정합니다.
지난 론칭때, 익명 게시판의 댓글이 실명으로 들어간 문제는 아마도 프론트에서 is_anonymous를 잘못 보내준 것이 아닐까 생각합니다.
(DB에서 해당 댓글의 is_anonymous가 False입니다)
여기서는 프론트에서 is_anonymous가 잘못 들어오더라도, 백에서 다시 확인해서 익명 글 / 익명 댓글에 대한 댓글은 is_anonymous 필드를 True로 바꿔줍니다.
익명 여부를 중복 확인하여 익명성을 보장하려 한 것인데, API 호출자가 주는 is_anonymous 필드를 무시하기 때문에 안좋은 디자인인지 조심스럽습니다.
안좋은 디자인이라면 말씀해주세요.
> Prevent non-anonymous comment on anonymous parent

- apps/core/views/viewsets/article.py
- tests/test_scrap.py
슬렉에서 문의하셨던 "[article 이 삭제될때, 관련 scrap 이 삭제되지 않는 문제](https://sparcs.slack.com/archives/CV6H8N4EM/p1641395417015100)"를 해결하는 PR입니다.
우선 문제가 발생했던 이유는
1. 유저가 직접 article delete API를 날리면,
2. article viewset의 destroy함수를 타게 됩니다.
3. destroy함수에는 get_object 함수가 있고, get_object함수는 제일 먼저 `self.filter_queryset(self.get_queryset())`를 실행시킵니다.
4. article viewset의 filter_queryset을 보면, 지금 action은 destroy로, list가 아니므로 else문을 타게 되고
5. 그러면 쿼리셋 prefetch_related 가 일어나는데, 보시면 `Scrap.prefetch_my_scrap(self.request.user),`가 있었습니다.
6. 그래서 article 중에서도, 내가 스크랩한것만 가져오게 됩니다.
7. 그러니까 그 article에서 .scrap_set.all() 로 스크랩세트를 가져오면, article이 parent_id로 있는 스크랩들 중에서도 내가 스크랩한것만 가져오게 됩니다. -> 그러니까 슬렉에서 이야기 하셨던 `(특이 사항: 본인이 본인글을 scrap 했을 경우, 이 scrap만 삭제가 됩니다)` 같은 현상이 발생하는것이죠. 반면, django admin페이지에서 delete를 시키면, 이 article viewset을 통해서 …
> Fix scrap not deleted when article deleted

- apps/core/models/notification.py
- tests/test_notification.py
대댓글 알림에서 related_comment가 기존에는 대댓글 self로 내려갔으나, 이제 parent_comment로 내려가도록 수정하였습니다.
> 대댓글 알림에서 related_comment가 parent_comment로 내려가도록 수정

- apps/core/views/viewsets/article.py
- tests/test_articles.py
기존에는 삭제된 게시글에 대하 GET request에 404를 리턴하였습니다.
사용자가 삭제된 글에 접근할 경우, 프론트에서 `삭제된 게시글입니다`로 보여주기 위해 410 Gone을 리턴하도록 수정하였습니다.
이제 처음부터 존재하지 않았던 글은 기존과 같이 404를, 삭제된 글은 410을 리턴하여 프론트에서 상황에 맞게 처리 가능합니다.
`viewsets/article.py`의 `retrieve()`를 수정하였습니다.
` article = self.get_object()`에서 글을 못찾을 경우를 try catch로 처리하여 삭제된 글일 경우 410을, 그 외는 404를 리턴합니다.
테스트 코드도 추가하였습니다.
> Return HTTP 410 for GET requests to deleted articles

- apps/core/serializers/article.py
프론트에서 게시판을 볼 때, 이미지가 있는 글은 제목 옆에 아이콘으로 표시해달라는 사용자 피드백이 있었습니다.
이에 따라, Article list view에서 각 article의 첨부파일 유무를 표현하는 has_attachments 필드를 추가하였습니다.
> Add has_attachments field to article list serializer

- apps/core/models/article.py
- apps/core/serializers/article.py
PR #301 에 대한 수정입니다.
게시판의 글들을 보여주는 article list view에서 attachment의 단순 유무 뿐만 아니라, 
`attachment_type` 필드를 통해 attachment의 종류까지 보여줍니다.
종류는 크게 4가지입니다: `NONE`, `IMAGE`, `NON_IMAGE`, `BOTH`
프론트에서 이미지가 있을 경우 게시판에 이미지 아이콘을, 이미지가 아닌 첨부파일이 있을 경우 게시판에 첨부 파일 아이콘을 띄워줄 것 입니다.
> Show attachment type (img/non-img) in article list view

- apps/core/management/scripts/portal_crawler.py
만약 공지 글 안 이미지가 포탈 주소가 아닌 경우에는 이상하게 extension이 붙는 경우가 있었는데 (ex: `files/portal_image_hash.https://....`), 이런 경우에는 그냥 바로 리턴해 줌으로써 해결해 주었습니다.
> Fix extension for the path that is not a portal url

- apps/core/models/article.py
- apps/core/models/comment.py
- apps/core/serializers/article.py
- apps/core/views/viewsets/comment.py
1. `article` 에  `my_comment_profile` 라는 필드를 추가했습니다. 기존에는 프론트에서 복잡한 방식으로 댓글 작성 창의 익명 여부와 프로필을 결정했지만, 실명까지 생김에 따라 프론트서 완벽히 구현이 불가능할 뿐더러 쉽게 버그가 날 가능성이 높아 보였습니다. 대신 간단히 백엔드에서 가짜 댓글을 만들어 `postprocessed_created_by` 에 의해 생성되는 **현재 요청을 보낸 사용자**의 댓글 프로필을 보내줍니다. `created_by` 와 완전히 구조가 같습니다.
2. 실명 게시판 목록에서 프로필 이미지로 `user_profile_picture_realname` 을 썼었던 방식을 없애기로 했습니다. (동명 이인을 굳이 구분 지을 필요는 없기 때문에)
3. 댓글이 실명인 경우에도 "글쓴이" 라는 텍스트가 보여지도록 했습니다.
기존의 프론트엔드에서 익명일때 어떻게 보여주었는지는 https://github.com/sparcs-kaist/new-ara-web/pull/313 의 diff 이전 코드를 참고해 주세요
> Add my_comment_profile field, minor fix

- apps/core/serializers/comment.py
`CommentSerializer`와 `CommentListActionSerializer`에 중복으로 존재하던 `created_by`를 하나씩 제거하였습니다.
> Remove duplicated created_by in CommentSerializer

- apps/core/views/viewsets/article.py
- tests/test_articles.py
실명게시판에서 좋아요 30개 이상일 때 취소할 수 없게 만들었습니다.
30개 이상일 때 취소하려고 시도하면 405가 나옵니다.
테스트 케이스도 추가했습니다.
> Add ban cancellation vote over threshold in realname article

- apps/core/management/scripts/portal_crawler.py
어제 작업한거랑 상관 없는 에러가 있어 고쳤어요.
장기적으로 한 글이 실패해도 전부가 실패하지 않는 로직으로 고쳐야합니다.
현재 N개 중 하나라도 fail하면 전체 실패하는 로직이라 우선은 이것만 고쳐서 배포해놓고 다음 티켓에서 try catch로 수정할게요
> fix portal crawler to handle exceptional html format

- .pre-commit-config.yaml
- .pylintrc
- poetry.lock
- pyproject.toml
기존의 pre commit hook들을 업데이트하였습니다.
(`.pre-commit-config.yaml` 파일 히스토리를 보면 PR #162 이후 한 번도 수정되지 않았습니다.)
Deprecated 된 [mirrors-pylint](https://github.com/pre-commit/mirrors-pylint)를 [pylint](https://github.com/pycqa/pylint)로 수정하는 작업을 진행하려 하였으나 Django 관련 에러를 해결하지 못해 일단은 제거하고 이후 해결하도록 하겠습니다.
Pre-commit hook을 사용하기 위해서는 터미널에 아래 명령을 입력해야 합니다. [(참고)](https://pre-commit.com/#3-install-the-git-hook-scripts)
```bash
pre-commit install
```
> Update pre commit hooks

- apps/user/models/user_profile.py
`UserProfile.is_official` is also `true` if email is <new-ara@sparcs.org>. (It is for putting a verified badge.)
> Make NewAra profile official

- apps/core/serializers/article.py
- apps/core/views/viewsets/comment.py
- apps/user/serializers/user_profile.py
- tests/conftest.py
- tests/test_comments.py
- tests/test_communication_article.py
1. "학교에게 전합니다" 게시판에서 school admin이 댓글을 작성했을 때 실명이 아닌 닉네임 타입으로 작성하게 변경했습니다.
2. Comment editor도 닉네임 타입으로 변경했습니다.
- Comment editor에도 공식마크 달기 위해서 프론트 작업이 필요할 것 같습니다.
4. 테스트 코드 작성했습니다.
> Fix school admin profile to nickname profile at comment

- apps/core/models/attachment.py
첨부파일 업로드 시 사용자가 작성한 파일명으로 업로드되던 로직을 `uuid4`를 사용하도록 수정하였습니다.
Related issue #52
> Use unique names for attachments

- .github/workflows/github-actions.yml
- ara/firebase.py
주의: 밥 서버가 죽게 되는 경우 runner가 돌지 못합니다. 이 경우 주석 처리한 부분으로 다시 되돌리셔야 합니다.
+ 추가: release를 위한 FCM 관련 부분을 비활성화 했습니다.
> Change runner to bap server & Disable FCM

- apps/core/serializers/article.py
GET `/articles/<id>/`
**Before**
```json
{
"attachments": [
[1],
[2],
[3]
]
}
```
**After**
```json
{
"attachments": [
{
"id": 1,
"created_at": "2023-06-17T18:08:22.264122+09:00",
"updated_at": "2023-06-17T18:08:22.264122+09:00",
"deleted_at": "0001-01-01T08:27:52+08:27:52",
"file": "...",
"size": 1234,
"mimetype": "image/png"
}
]
}
```
> Include attachment details in the article's detailed response

- apps/core/views/viewsets/article.py
Join `boardgroup` table when selecting articles:
```sql
SELECT ...
FROM `core_article`
...
INNER JOIN `core_board`
ON (`core_article`.`parent_board_id` = `core_board`.`id`)
LEFT OUTER JOIN `core_boardgroup`
ON (`core_board`.`group_id` = `core_boardgroup`.`id`)
...
```
> Fix article board group N+1 query problem

- .pre-commit-config.yaml
- apps/core/serializers/article.py
- apps/core/views/viewsets/article.py
[관련 슬랙 스레드](https://sparcs.slack.com/archives/CV6H8N4EM/p1688993413333279)
이 외 변경사항은 pre-commit이 작동 안되서 `pre-commit autoupdate` 돌리면서 생긴 것들 입니다.
> Add minor features for top articles

- .vscode/settings.json
- Pipfile
- Pipfile.lock
- mypy.ini
To enable vscode mypy settings.
Added stubs to make django and djangorestframework not to make typehint errors.
* mypy.ini - linting settings
* vscode/settings.json set mypy to default linter.
* Pipfile - add django-stubs djangorestframework-stubs to fix mypy linting errors.
> feat(mypy): add stubs to remove mypy linting errors

- .pre-commit-config.yaml
- README.md
**Updates**
- Use `pre-commit` for linting codes and commit messages.
- Use `pipenv` for package management.
> Update docs and define coding styles

- apps/core/migrations/0057_alter_article_name_type_and_more.py
- apps/core/models/article.py
- Discussion message: https://sparcs.slack.com/archives/CV6H8N4EM/p1704937104870679
- created_at 대신 id로 정렬하는 안 -> 다음 이유로 보류
- id로 정렬하는 경우, 외부로부터 article을 export 해오는 경우 created_at과 id의 순서가 다를 수 있음 (e.g. 포탈 크롤러)
- 기타 고려 사항:
1) 어쨌든 composite index는 생성해야해서 (id, parent_board_id)를 생성하도록 수정했는데, 해당 index 생성이 이전과 마찬가지로 DB에 부하를 줄 가능성이 있음
2) 프론트엔드에서 GET /articles?ordering=-created_at 으로 최신순 정렬하는 경우를 모두 GET /articles?ordering=-id로 바꿔주어야 함
- Slow Query의 근본적인 원인이 created_at index의 부재가 아니였기 때문에 일단 index를 없애버림
> [Hotfix] Remove index using created_at to prevent performance issue

- .github/workflows/github-actions.yml
- apps/core/views/viewsets/article.py
- tests/test_articles.py
기존 인기 개시판은 전체 기간에 대해서 불러오기 때문에 시간이 너무 느립니다.
해당 endpoint 를 최근 1주일내에 만들어진 개시물을 조회수 기준으로 sorting해서 내려줍니다
> fix top k policy

- apps/core/serializers/article.py
> fix: bugfix for top query

- apps/core/management/tasks.py
과거 학식을 가져오는 경우 학식 정보가 변경된 경우 대응할 수 있는 방안이 아직 마련되어 있지 않음. (정규식 검사를 통과하지 못 해서 오류가 발생한다.) 따라서 현재 날짜를 기준으로 앞으로 7일간의 학식 정보만 크롤링 해 오는 것으로 바꾸었다.
> [Hotfix] 학식 크롤링 기능 기한 조정

- apps/kaist/portal/worker.py
닉네임 중복 에러를 막기 위해 포탈 공지는 작성자를 KAIST Portal로 표시합니다.
> portal_crawler_policy 변경
